### ISSUE TITLE
Rake db:setup not working 

### ISSUE THREAD

**Issue by johnp2686** [srcclr/commit-watcher#15]
I setup locally commit watcher when i ran rake db:setup getting error

warning: constant ::Fixnum is deprecated
rake aborted!
Sequel::DatabaseConnectionError: Mysql2::Error: Unknown MySQL server host 'db' (0)

I mentioned host in database.yml file but still i am getting same error any one can help me on this

**Comment by newbishme** [comment]
@johnp2686 May I ask for a sample of your database.yml, with your db and credentials masked?

Specifically, if you were using a non-local DB, I was wondering if you have commented this line: https://github.com/srcclr/commit-watcher/blob/master/config/database.yml#L8

**Comment by johnp2686** [comment]
@newbishme  my database.yml  i am using localdb not remote one

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: "***"
  host: localhost
  # Use this for local mysql instances
  socket: /tmp/mysql.sock

  # Use this for Docker
  #host: db

  # Use this for External RDS
  #host: <%= ENV['COMMIT_WATCHER_EXTERNAL_DATABASE_URL'] %>

development:
  <<: *default
  database: commit_watcher_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: commit_watcher_test

production:
  <<: *default
  username: commit_watcher
  password: <%= ENV['COMMIT_WATCHER_DATABASE_PASSWORD'] %>
  database: commit_watcher_production

Can you help on this

**Comment by newbishme** [comment]
@johnp2686 when using a local DB, you can use the database.yml as-is (aside from your database name and credential)

Ensure that:

1. https://github.com/srcclr/commit-watcher/blob/master/config/database.yml#L8 is uncommented,
2. host: is commented.

In your case, the default configuration would work.

```# Use this for local mysql instances
  socket: /tmp/mysql.sock

  # Use this for Docker
  #host: db

  # Use this for External RDS
  #host: <%= ENV['COMMIT_WATCHER_EXTERNAL_DATABASE_URL'] %>
```

The usage of `host: db` shown in the configuration is **only** for deployments via Docker. (eg. docker-compose up)

**Comment by johnp2686** [comment]
@newbishme  I make configure everything when a  ran rake db:setup getting this error :

D, [2017-12-04T11:44:25.676612 #3230] DEBUG -- :   Sequel::Mysql2::Database (0.3ms)  SET NAMES utf8
D, [2017-12-04T11:44:25.676888 #3230] DEBUG -- :   Sequel::Mysql2::Database (0.1ms)  SET @@wait_timeout = 2147483
D, [2017-12-04T11:44:25.677096 #3230] DEBUG -- :   Sequel::Mysql2::Database (0.1ms)  SET SQL_AUTO_IS_NULL=0
D, [2017-12-04T11:44:27.617088 #3230] DEBUG -- :   Sequel::Mysql2::Database (0.7ms)  DESCRIBE `commits`
D, [2017-12-04T11:44:27.617833 #3230] DEBUG -- :   Sequel::Mysql2::Database (0.4ms)  SELECT * FROM `commits` LIMIT 1
rake aborted!
Sequel::DatabaseError: Mysql2::Error: Table 'commit_watcher_development.commits' doesn't exist

Can you help on this

**Comment by newbishme** [comment]
@johnp2686 It seems that `rake db:setup` is not creating the tables for you. Would be great if you could verify that the database, `commit_watcher_development`, was created. If it is not, you can try creating it manually in mysql, `create database commit_watcher_development;`, and then retry the `rake db:setup` command.

**Comment by johnp2686** [comment]
@newbishme  I create database manually and run `rake db:setup` still i getting same error

**Comment by newbishme** [comment]
@johnp2686 After going through some possibilities, I do not have enough to debug this information. By any chance, do you have a more complete log from `rake db:setup`? The current snippet does not tell me if the tables were being created. If it was, it should create the tables such as `commits`.

**Comment by halkeye** [comment]
I'm mobile right now so can't check but does rake db:create still exist? Does that work? Does it show any extra error messages?

**Comment by malhanpraveen** [comment]
I am also facing the same issue with rake db:setup. Can someone help?

**Comment by newbishme** [comment]
@malhanpraveen The error you faced is not the same as the original issue. In this case, the authentication to the DB has failed, which should be easy to resolve and retry. Please ensure that you have set the correct DB credentials to match your local MySQL database credentials.

**Comment by newbishme** [comment]
@johnp2686 hey, sorry it has been awhile. I have found that the cause of issue is due to an update in the dependencies `mysql2` and `sequel`. I have now specified the version that works in [this commit](https://github.com/srcclr/commit-watcher/commit/025c4f6e485e44bf8c20d82f3c9582cccb788fa1) and it should now properly create the tables and all.
